### ISSUE TITLE
Adicionar importação de outros formatos

### ISSUE THREAD

**Issue by cccadet** [cccadet/personal-search#6]
## TODO:
- [x] Implement pdf import
- [ ] Implement doc,docx import
- [ ] Implement txt import
- [ ] Implement epub import
